### ISSUE TITLE
can't load mongodb 

### ISSUE THREAD

**Issue by lrl219** [thetatoken/theta-protocol-ledger#100]
go: finding github.com/golang/protobuf v1.4.0-rc.4.0.20200313231945-b860323f09d0
go: finding github.com/libp2p/go-libp2p-yamux v0.2.7
go: finding github.com/chzyer/logex v1.1.10
go: finding github.com/ipfs/go-ds-badger v0.2.1
go: finding github.com/libp2p/go-libp2p-autonat v0.2.2
go: finding github.com/libp2p/go-libp2p-core v0.4.0
go: finding github.com/libp2p/go-libp2p-secio v0.2.2
go: finding github.com/libp2p/go-libp2p-swarm v0.2.2
go: finding github.com/libp2p/go-libp2p-yamux v0.2.2
go: finding github.com/libp2p/go-libp2p-blankhost v0.1.4
go: finding github.com/ipfs/go-datastore v0.1.0
go: finding github.com/ipfs/go-ds-badger v0.0.7
go: finding github.com/libp2p/go-libp2p-secio v0.2.1
go: finding github.com/dgraph-io/badger v1.6.0
go: finding github.com/libp2p/go-eventbus v0.1.0
go: finding github.com/libp2p/go-libp2p-core v0.3.0
go: finding github.com/ipfs/go-datastore v0.4.0
go: finding github.com/libp2p/go-libp2p-core v0.2.2
go: finding github.com/chzyer/readline v0.0.0-20180603132655-2972be24d48e
go: finding github.com/ipfs/go-ds-leveldb v0.4.1
go: finding github.com/libp2p/go-libp2p v0.7.4
go: finding github.com/multiformats/go-multiaddr-net v0.1.0
go: finding github.com/libp2p/go-ws-transport v0.3.0
go: finding github.com/multiformats/go-multiaddr v0.1.0
go: finding google.golang.org/protobuf v1.20.1-0.20200309200217-e05f789c0967
go: finding github.com/libp2p/go-yamux v1.3.0
go: finding github.com/libp2p/go-yamux v1.3.5
go: finding github.com/libp2p/go-openssl v0.0.2
go: finding github.com/golang/protobuf v1.4.0-rc.2
go: finding github.com/libp2p/go-libp2p-autonat v0.2.1
go: finding google.golang.org/protobuf v0.0.0-20200228230310-ab0ca4ff8a60
go: finding github.com/libp2p/go-libp2p v0.7.0
go: finding github.com/golang/protobuf v1.4.0-rc.1.0.20200221234624-67d41d38c208
go: finding github.com/libp2p/go-libp2p-autonat v0.2.0
go: finding github.com/libp2p/go-libp2p-circuit v0.1.4
go: finding github.com/libp2p/go-libp2p-yamux v0.2.5
go: finding github.com/libp2p/go-libp2p-peerstore v0.2.1
go: finding github.com/libp2p/go-libp2p-discovery v0.2.0
go: finding github.com/libp2p/go-ws-transport v0.2.0
go: finding github.com/miekg/dns v1.1.28
go: finding github.com/libp2p/go-libp2p-mplex v0.2.2
go: finding github.com/libp2p/go-libp2p-nat v0.0.5
go: finding google.golang.org/protobuf v0.0.0-20200221191635-4d8936d0db64
go: finding github.com/libp2p/go-libp2p v0.6.1
go: finding github.com/libp2p/go-yamux v1.3.3
go: finding github.com/whyrusleeping/go-logging v0.0.1
go: finding github.com/gorilla/websocket v1.4.1
go: finding github.com/golang/protobuf v1.4.0-rc.1
go: finding github.com/google/go-cmp v0.3.1
go: finding github.com/libp2p/go-mplex v0.1.1
go: finding github.com/libp2p/go-nat v0.0.4
go: finding github.com/libp2p/go-libp2p-autonat v0.1.1
go: finding golang.org/x/crypto v0.0.0-20200221231518-2aa609cf4a9d
go: finding github.com/libp2p/go-libp2p-peerstore v0.2.0
go: finding google.golang.org/protobuf v0.0.0-20200109180630-ec00e32a8dfd
go: downloading golang.org/x/crypto v0.0.0-20200423211502-4bdfaf469ed5
go: downloading github.com/yuin/gopher-lua v0.0.0-20200816102855-ee81675732da
go: downloading github.com/golang/protobuf v1.4.0
go: downloading github.com/libp2p/go-libp2p v0.12.0
go: downloading github.com/google/uuid v1.1.2
go: downloading github.com/ipfs/go-datastore v0.4.5
go: downloading github.com/libp2p/go-libp2p-kbucket v0.4.7
go: extracting github.com/yuin/gopher-lua v0.0.0-20200816102855-ee81675732da
go: extracting github.com/golang/protobuf v1.4.0
go: extracting github.com/google/uuid v1.1.2
go: extracting github.com/ipfs/go-datastore v0.4.5
go: extracting github.com/libp2p/go-libp2p v0.12.0
go: extracting github.com/libp2p/go-libp2p-kbucket v0.4.7
go: downloading github.com/ipfs/go-ipns v0.0.2
go: downloading github.com/libp2p/go-libp2p-asn-util v0.0.0-20200825225859-85005c6cf052
go: downloading github.com/libp2p/go-libp2p-record v0.1.3
go: downloading github.com/libp2p/go-tcp-transport v0.2.1
go: extracting golang.org/x/crypto v0.0.0-20200423211502-4bdfaf469ed5
go: extracting github.com/ipfs/go-ipns v0.0.2
go: downloading github.com/ipfs/go-ipfs-util v0.0.2
go: extracting github.com/libp2p/go-libp2p-record v0.1.3
go: extracting github.com/libp2p/go-tcp-transport v0.2.1
go: downloading google.golang.org/protobuf v1.23.0
go: downloading github.com/libp2p/go-libp2p-tls v0.1.3
go: downloading github.com/google/gopacket v1.1.18
go: extracting github.com/ipfs/go-ipfs-util v0.0.2
go: extracting github.com/libp2p/go-libp2p-tls v0.1.3
go: downloading github.com/libp2p/go-ws-transport v0.3.1
go: downloading github.com/ipfs/go-log/v2 v2.1.1
go: downloading github.com/opentracing/opentracing-go v1.2.0
go: extracting github.com/libp2p/go-libp2p-asn-util v0.0.0-20200825225859-85005c6cf052
go: downloading github.com/libp2p/go-reuseport v0.0.2
go: downloading github.com/libp2p/go-libp2p-noise v0.1.1
go: extracting github.com/libp2p/go-ws-transport v0.3.1
go: extracting github.com/ipfs/go-log/v2 v2.1.1
go: extracting google.golang.org/protobuf v1.23.0
go: extracting github.com/opentracing/opentracing-go v1.2.0
go: downloading github.com/libp2p/go-libp2p-circuit v0.4.0
go: extracting github.com/libp2p/go-libp2p-noise v0.1.1
go: extracting github.com/libp2p/go-reuseport v0.0.2
go: extracting github.com/google/gopacket v1.1.18
go: extracting github.com/libp2p/go-libp2p-circuit v0.4.0
go: downloading github.com/libp2p/go-reuseport-transport v0.0.4
go: downloading github.com/hashicorp/go-multierror v1.1.0
go: downloading github.com/gorilla/websocket v1.4.2
go: extracting github.com/libp2p/go-reuseport-transport v0.0.4
go: extracting github.com/hashicorp/go-multierror v1.1.0
go: extracting github.com/gorilla/websocket v1.4.2
go: downloading github.com/jackpal/go-nat-pmp v1.0.2
go: downloading github.com/multiformats/go-multiaddr-dns v0.2.0
go: downloading github.com/libp2p/go-netroute v0.1.3
go: downloading github.com/hashicorp/errwrap v1.0.0
go: extracting github.com/multiformats/go-multiaddr-dns v0.2.0
go: downloading github.com/koron/go-ssdp v0.0.0-20191105050749-2e1c40ed0b5d
go: extracting github.com/hashicorp/errwrap v1.0.0
go: downloading github.com/flynn/noise v0.0.0-20180327030543-2492fe189ae6
go: extracting github.com/jackpal/go-nat-pmp v1.0.2
go: extracting github.com/libp2p/go-netroute v0.1.3
go: extracting github.com/flynn/noise v0.0.0-20180327030543-2492fe189ae6
go: downloading github.com/libp2p/go-libp2p-autonat v0.4.0
go: extracting github.com/koron/go-ssdp v0.0.0-20191105050749-2e1c40ed0b5d
go: downloading github.com/libp2p/go-cidranger v1.1.0
go: downloading github.com/libp2p/go-libp2p-mplex v0.3.0
go: downloading github.com/libp2p/go-libp2p-nat v0.0.6
go: downloading go.uber.org/zap v1.16.0
go: downloading github.com/libp2p/go-libp2p-blankhost v0.2.0
go: extracting github.com/libp2p/go-libp2p-autonat v0.4.0
go: extracting github.com/libp2p/go-cidranger v1.1.0
go: extracting github.com/libp2p/go-libp2p-mplex v0.3.0
go: downloading github.com/libp2p/go-mplex v0.2.0
go: extracting github.com/libp2p/go-libp2p-nat v0.0.6
go: extracting go.uber.org/zap v1.16.0
go: downloading github.com/libp2p/go-nat v0.0.5
go: extracting github.com/libp2p/go-libp2p-blankhost v0.2.0
go: extracting github.com/libp2p/go-mplex v0.2.0
go: extracting github.com/libp2p/go-nat v0.0.5
go: github.com/mongodb/mongo-go-driver@v1.4.4: parsing go.mod: unexpected module path "go.mongodb.org/mongo-driver"
go: error loading module requirements
make: *** [r

**Comment by jieyilong** [comment]
Hmm do you mind share your Ubuntu and golang version? And just to confirm -- you have switched the go11 module support on `export GO111MODULE=on`, right?

**Comment by lrl219** [comment]
os : macOS big sur
go version : go version go1.12.10 darwin/amd64
GO111MODULE=on, yes

**Comment by lrl219** [comment]
> Hmm do you mind share your Ubuntu and golang version? And just to confirm -- you have switched the go11 module support on `export GO111MODULE=on`, right?



> Hmm do you mind share your Ubuntu and golang version? And just to confirm -- you have switched the go11 module support on `export GO111MODULE=on`, right?

os : macOS big sur
go version : go version go1.12.10 darwin/amd64
GO111MODULE=on, yes

**Comment by lrl219** [comment]
My former go version is 1.15 and the file /rpc/lib/rpc-codec/go.mod was rewriten with go version 1.15 by goland editor.After stash and rerun `make install`, issue resolved.
