### ISSUE TITLE
How to synchronize full nodes? How much disk space is required for full nodes?

### ISSUE THREAD

**Issue by Black52** [thetatoken/theta-protocol-ledger#119]
I am now synchronizing the mainnet to be useing snapshots:
wget -O ../mainnet/walletnode/snapshot `curl -k https://mainnet-data.thetatoken.org/snapshot`
But there's no historical data,
How to synchronize all nodes? 
Is there a snapshot of the full node?   How much disk space is required for full nodes?

**Comment by Lionel2298** [comment]
Hello Mate, Sorry to hear about your issue, you can contact the Theta Network Support on Telegram via the weblink www.t.me/thetanetworking. They'll be happy to resolve your issue. Cheers.

**Comment by TomJ801** [comment]
> I am now synchronizing the mainnet to be useing snapshots:
> wget -O ../mainnet/walletnode/snapshot `curl -k https://mainnet-data.thetatoken.org/snapshot`
> But there's no historical data,
> How to synchronize all nodes?
> Is there a snapshot of the full node? How much disk space is required for full nodes?
Hello mate have you resolved the issue ?

**Comment by giovannirco** [comment]
To have historical data you need to use the snapshot from [this](https://github.com/thetatoken/theta-protocol-ledger/tree/master/integration/mainnet/walletnode) folder

Although I was able to start syncing from block 0 it is painfully slow and I have no idea how to make it go faster :/
