### ISSUE TITLE
make install failed

### ISSUE THREAD

**Issue by vae520283995** [thetatoken/theta-protocol-ledger#128]
Failed to build node according to official documentation https://docs.thetatoken.org/docs/setup

root@ip-172-31-36-185:~/go/src/github.com/thetatoken/theta# make install
go install ./cmd/...
go: finding github.com/sirupsen/logrus v1.2.0
go: finding github.com/mattn/go-colorable v0.1.7
go: finding github.com/huin/goupnp v0.0.0-20180415215157-1395d1447324
go: finding github.com/grpc-ecosystem/go-grpc-middleware v1.0.0
go: finding github.com/mitchellh/mapstructure v1.1.2
go: finding github.com/xordataexchange/crypt v0.0.3-0.20170626215501-b2862e3d0a77
go: finding github.com/prometheus/client_golang v0.9.3
go: finding github.com/xiang90/probing v0.0.0-20190116061207-43a291ad63a2
go: finding golang.org/x/net v0.0.0-20190522155817-f3200d17e092
go: finding github.com/coreos/bbolt v1.3.2
go: finding go.uber.org/zap v1.10.0
go: finding github.com/wedeploy/gosocketio v0.0.7-beta
go: finding github.com/ipfs/go-ipfs-delay v0.0.0-20181109222059-70721b86a9a8
go: finding github.com/go-check/check v0.0.0-20180628173108-788fd7840127
go: finding github.com/libp2p/go-stream-muxer-multistream v0.2.0
go: github.com/wedeploy/gosocketio@v0.0.7-beta: unknown revision v0.0.7-beta
go: finding golang.org/x/net v0.0.0-20181011144130-49bb7cea24b1
go: finding github.com/spf13/cast v1.3.0
go: finding github.com/libp2p/go-libp2p-loggables v0.1.0
go: finding github.com/miekg/dns v1.1.12
go: finding go.uber.org/atomic v1.4.0
go: finding golang.org/x/text v0.3.0
go: finding github.com/btcsuite/goleveldb v0.0.0-20160330041536-7834afc9e8cd
go: finding github.com/libp2p/go-libp2p-circuit v0.1.1
go: finding github.com/fsnotify/fsnotify v1.4.7
go: finding gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
go: finding golang.org/x/sys v0.0.0-20180905080454-ebe1bf3edb33
go: finding github.com/pion/sctp v1.7.3
go: finding github.com/spf13/jwalterweatherman v1.0.0
go: finding github.com/google/go-cmp v0.2.0
go: finding github.com/google/uuid v1.1.1
go: finding github.com/jbenet/go-cienv v0.1.0
go: finding github.com/onsi/gomega v1.4.3
go: finding golang.org/x/net v0.0.0-20190311183353-d8887717615a
go: finding golang.org/x/crypto v0.0.0-20181203042331-505ab145d0a9
go: finding golang.org/x/sys v0.0.0-20190412213103-97732733099d
go: finding github.com/libp2p/go-maddr-filter v0.0.5
go: finding github.com/coreos/etcd v3.3.10+incompatible
go: finding gopkg.in/check.v1 v1.0.0-20190902080502-41f04d3bba15
go: finding github.com/mgutz/ansi v0.0.0-20200706080929-d51e80ef957d
go: finding github.com/gorilla/websocket v1.4.0
go: finding github.com/konsorten/go-windows-terminal-sequences v1.0.1
go: finding github.com/btcsuite/btclog v0.0.0-20170628155309-84c8d2346e9f
go: finding github.com/kkdai/bstream v0.0.0-20161212061736-f391b8402d23
go: finding gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127
go: finding github.com/grpc-ecosystem/go-grpc-prometheus v1.2.0
go: finding github.com/ipfs/go-ipfs-util v0.0.1
go: finding github.com/libp2p/go-libp2p-yamux v0.2.1
go: finding github.com/libp2p/go-libp2p-mplex v0.2.1
go: finding github.com/libp2p/go-libp2p-netutil v0.1.0
go: finding github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: finding github.com/soheilhy/cmux v0.1.4
go: finding github.com/subosito/gotenv v1.2.0
go: finding go.uber.org/multierr v1.1.0
go: finding github.com/libp2p/go-libp2p-blankhost v0.1.3
go: finding golang.org/x/crypto v0.0.0-20170930174604-9419663f5a44
go: finding github.com/ugorji/go/codec v0.0.0-20181204163529-d75b2dcb6bc8
go: finding github.com/spf13/afero v1.1.2
go: finding github.com/btcsuite/btcutil v0.0.0-20190207003914-4c204d697803
go: finding github.com/jrick/logrotate v1.0.0
go: finding golang.org/x/net v0.0.0-20180524181706-dfa909b99c79
go: finding github.com/libp2p/go-libp2p-autonat v0.1.0
go: finding golang.org/x/crypto v0.0.0-20180904163835-0709b304e793
go: finding github.com/libp2p/go-ws-transport v0.1.0
go: finding golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: finding github.com/huin/goutil v0.0.0-20170803182201-1ca381bf3150
go: finding github.com/whyrusleeping/mdns v0.0.0-20180901202407-ef14215e6b30
go: finding github.com/hashicorp/hcl v1.0.0
go: finding github.com/coreos/go-etcd v2.0.0+incompatible
go: finding github.com/btcsuite/winsvc v1.0.0
go: finding github.com/golang/groupcache v0.0.0-20190129154638-5b532d6fd5ef
go: finding google.golang.org/genproto v0.0.0-20190307195333-5fe7a883aa19
go: finding github.com/davecgh/go-spew v0.0.0-20171005155431-ecdeabc65495
go: finding github.com/multiformats/go-multiaddr-dns v0.0.2
go: finding golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: finding github.com/libp2p/go-libp2p-secio v0.2.0
go: finding golang.org/x/sys v0.0.0-20181205085412-a5c9d58dba9a
go: finding github.com/libp2p/go-tcp-transport v0.1.0
go: finding golang.org/x/sys v0.0.0-20190422165155-953cdadca894
go: finding github.com/tmc/grpc-websocket-proxy v0.0.0-20190109142713-0ad062ec5ee5
go: finding github.com/pelletier/go-toml v1.2.0
go: finding google.golang.org/grpc v1.19.0
go: finding github.com/coreos/go-systemd v0.0.0-20190321100706-95778dfbb74e
go: finding github.com/libp2p/go-libp2p-transport-upgrader v0.1.1
go: finding golang.org/x/net v0.0.0-20190404232315-eb5bcb51f2a3
go: finding github.com/libp2p/go-eventbus v0.0.2
go: finding github.com/stretchr/objx v0.1.1
go: finding github.com/libp2p/go-libp2p-discovery v0.1.0
go: finding github.com/golang/protobuf v1.2.0
go: finding github.com/stretchr/testify v1.2.2
go: finding github.com/magiconair/properties v1.8.1
go: finding github.com/libp2p/go-conn-security-multistream v0.1.0
go: finding github.com/armon/consul-api v0.0.0-20180202201655-eb2c6b5be1b6
go: finding github.com/libp2p/go-libp2p-nat v0.0.4
go: finding github.com/coreos/go-semver v0.2.0
go: finding github.com/ugorji/go v1.1.4
go: finding github.com/libp2p/go-libp2p-testing v0.1.0
go: finding github.com/btcsuite/snappy-go v0.0.0-20151229074030-0bdef8d06723
go: finding github.com/btcsuite/websocket v0.0.0-20150119174127-31079b680792
go: finding github.com/coreos/pkg v0.0.0-20180928190104-399ea9e2e55f
go: finding github.com/grpc-ecosystem/grpc-gateway v1.9.0
go: finding github.com/magiconair/properties v1.8.0
go: finding google.golang.org/grpc v1.21.0
go: finding github.com/btcsuite/go-socks v0.0.0-20170105172521-4720035b7bfd
go: finding go.etcd.io/bbolt v1.3.2
go: finding golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
go: finding github.com/hashicorp/golang-lru v0.5.0
go: finding github.com/jackpal/gateway v1.0.4
go: finding github.com/aead/siphash v1.0.1
go: finding github.com/jonboulle/clockwork v0.1.0
go: finding github.com/kr/pretty v0.1.0
go: finding github.com/onsi/ginkgo v1.7.0
go: finding github.com/google/btree v1.0.0
go: finding github.com/jessevdk/go-flags v0.0.0-20141203071132-1679536dcc89
go: finding github.com/russross/blackfriday v1.5.2
go: error loading module requirements
Makefile:26: recipe for target 'release' failed
make: *** [release] Error 1
root@ip-172-31-36-185:~/go/src/github.com/thetatoken/theta# go version
go version go1.12.1 linux/amd64
root@ip-172-31-36-185:~/go/src/github.com/thetatoken/theta# uname -a
Linux ip-172-31-36-185 5.4.0-1038-aws #40~18.04.1-Ubuntu SMP Sat Feb 6 01:56:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by networkpunk** [comment]
I had the same issue, installed the latest version of Go (instead of the quoted 1.12 in the docs) and it all worked as expected.

**Comment by FrankP01** [comment]
> Failed to build node according to official documentation https://docs.thetatoken.org/docs/setup
> 
> root@ip-172-31-36-185:~/go/src/github.com/thetatoken/theta# make install go install ./cmd/... go: finding github.com/sirupsen/logrus v1.2.0 go: finding github.com/mattn/go-colorable v0.1.7 go: finding github.com/huin/goupnp v0.0.0-20180415215157-1395d1447324 go: finding github.com/grpc-ecosystem/go-grpc-middleware v1.0.0 go: finding github.com/mitchellh/mapstructure v1.1.2 go: finding github.com/xordataexchange/crypt v0.0.3-0.20170626215501-b2862e3d0a77 go: finding github.com/prometheus/client_golang v0.9.3 go: finding github.com/xiang90/probing v0.0.0-20190116061207-43a291ad63a2 go: finding golang.org/x/net v0.0.0-20190522155817-f3200d17e092 go: finding github.com/coreos/bbolt v1.3.2 go: finding go.uber.org/zap v1.10.0 go: finding github.com/wedeploy/gosocketio v0.0.7-beta go: finding github.com/ipfs/go-ipfs-delay v0.0.0-20181109222059-70721b86a9a8 go: finding github.com/go-check/check v0.0.0-20180628173108-788fd7840127 go: finding github.com/libp2p/go-stream-muxer-multistream v0.2.0 go: github.com/wedeploy/gosocketio@v0.0.7-beta: unknown revision v0.0.7-beta go: finding golang.org/x/net v0.0.0-20181011144130-49bb7cea24b1 go: finding github.com/spf13/cast v1.3.0 go: finding github.com/libp2p/go-libp2p-loggables v0.1.0 go: finding github.com/miekg/dns v1.1.12 go: finding go.uber.org/atomic v1.4.0 go: finding golang.org/x/text v0.3.0 go: finding github.com/btcsuite/goleveldb v0.0.0-20160330041536-7834afc9e8cd go: finding github.com/libp2p/go-libp2p-circuit v0.1.1 go: finding github.com/fsnotify/fsnotify v1.4.7 go: finding gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405 go: finding golang.org/x/sys v0.0.0-20180905080454-ebe1bf3edb33 go: finding github.com/pion/sctp v1.7.3 go: finding github.com/spf13/jwalterweatherman v1.0.0 go: finding github.com/google/go-cmp v0.2.0 go: finding github.com/google/uuid v1.1.1 go: finding github.com/jbenet/go-cienv v0.1.0 go: finding github.com/onsi/gomega v1.4.3 go: finding golang.org/x/net v0.0.0-20190311183353-d8887717615a go: finding golang.org/x/crypto v0.0.0-20181203042331-505ab145d0a9 go: finding golang.org/x/sys v0.0.0-20190412213103-97732733099d go: finding github.com/libp2p/go-maddr-filter v0.0.5 go: finding github.com/coreos/etcd v3.3.10+incompatible go: finding gopkg.in/check.v1 v1.0.0-20190902080502-41f04d3bba15 go: finding github.com/mgutz/ansi v0.0.0-20200706080929-d51e80ef957d go: finding github.com/gorilla/websocket v1.4.0 go: finding github.com/konsorten/go-windows-terminal-sequences v1.0.1 go: finding github.com/btcsuite/btclog v0.0.0-20170628155309-84c8d2346e9f go: finding github.com/kkdai/bstream v0.0.0-20161212061736-f391b8402d23 go: finding gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127 go: finding github.com/grpc-ecosystem/go-grpc-prometheus v1.2.0 go: finding github.com/ipfs/go-ipfs-util v0.0.1 go: finding github.com/libp2p/go-libp2p-yamux v0.2.1 go: finding github.com/libp2p/go-libp2p-mplex v0.2.1 go: finding github.com/libp2p/go-libp2p-netutil v0.1.0 go: finding github.com/dgrijalva/jwt-go v3.2.0+incompatible go: finding github.com/soheilhy/cmux v0.1.4 go: finding github.com/subosito/gotenv v1.2.0 go: finding go.uber.org/multierr v1.1.0 go: finding github.com/libp2p/go-libp2p-blankhost v0.1.3 go: finding golang.org/x/crypto v0.0.0-20170930174604-9419663f5a44 go: finding github.com/ugorji/go/codec v0.0.0-20181204163529-d75b2dcb6bc8 go: finding github.com/spf13/afero v1.1.2 go: finding github.com/btcsuite/btcutil v0.0.0-20190207003914-4c204d697803 go: finding github.com/jrick/logrotate v1.0.0 go: finding golang.org/x/net v0.0.0-20180524181706-dfa909b99c79 go: finding github.com/libp2p/go-libp2p-autonat v0.1.0 go: finding golang.org/x/crypto v0.0.0-20180904163835-0709b304e793 go: finding github.com/libp2p/go-ws-transport v0.1.0 go: finding golang.org/x/time v0.0.0-20190308202827-9d24e82272b4 go: finding github.com/huin/goutil v0.0.0-20170803182201-1ca381bf3150 go: finding github.com/whyrusleeping/mdns v0.0.0-20180901202407-ef14215e6b30 go: finding github.com/hashicorp/hcl v1.0.0 go: finding github.com/coreos/go-etcd v2.0.0+incompatible go: finding github.com/btcsuite/winsvc v1.0.0 go: finding github.com/golang/groupcache v0.0.0-20190129154638-5b532d6fd5ef go: finding google.golang.org/genproto v0.0.0-20190307195333-5fe7a883aa19 go: finding github.com/davecgh/go-spew v0.0.0-20171005155431-ecdeabc65495 go: finding github.com/multiformats/go-multiaddr-dns v0.0.2 go: finding golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2 go: finding github.com/libp2p/go-libp2p-secio v0.2.0 go: finding golang.org/x/sys v0.0.0-20181205085412-a5c9d58dba9a go: finding github.com/libp2p/go-tcp-transport v0.1.0 go: finding golang.org/x/sys v0.0.0-20190422165155-953cdadca894 go: finding github.com/tmc/grpc-websocket-proxy v0.0.0-20190109142713-0ad062ec5ee5 go: finding github.com/pelletier/go-toml v1.2.0 go: finding google.golang.org/grpc v1.19.0 go: finding github.com/coreos/go-systemd v0.0.0-20190321100706-95778dfbb74e go: finding github.com/libp2p/go-libp2p-transport-upgrader v0.1.1 go: finding golang.org/x/net v0.0.0-20190404232315-eb5bcb51f2a3 go: finding github.com/libp2p/go-eventbus v0.0.2 go: finding github.com/stretchr/objx v0.1.1 go: finding github.com/libp2p/go-libp2p-discovery v0.1.0 go: finding github.com/golang/protobuf v1.2.0 go: finding github.com/stretchr/testify v1.2.2 go: finding github.com/magiconair/properties v1.8.1 go: finding github.com/libp2p/go-conn-security-multistream v0.1.0 go: finding github.com/armon/consul-api v0.0.0-20180202201655-eb2c6b5be1b6 go: finding github.com/libp2p/go-libp2p-nat v0.0.4 go: finding github.com/coreos/go-semver v0.2.0 go: finding github.com/ugorji/go v1.1.4 go: finding github.com/libp2p/go-libp2p-testing v0.1.0 go: finding github.com/btcsuite/snappy-go v0.0.0-20151229074030-0bdef8d06723 go: finding github.com/btcsuite/websocket v0.0.0-20150119174127-31079b680792 go: finding github.com/coreos/pkg v0.0.0-20180928190104-399ea9e2e55f go: finding github.com/grpc-ecosystem/grpc-gateway v1.9.0 go: finding github.com/magiconair/properties v1.8.0 go: finding google.golang.org/grpc v1.21.0 go: finding github.com/btcsuite/go-socks v0.0.0-20170105172521-4720035b7bfd go: finding go.etcd.io/bbolt v1.3.2 go: finding golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a go: finding github.com/hashicorp/golang-lru v0.5.0 go: finding github.com/jackpal/gateway v1.0.4 go: finding github.com/aead/siphash v1.0.1 go: finding github.com/jonboulle/clockwork v0.1.0 go: finding github.com/kr/pretty v0.1.0 go: finding github.com/onsi/ginkgo v1.7.0 go: finding github.com/google/btree v1.0.0 go: finding github.com/jessevdk/go-flags v0.0.0-20141203071132-1679536dcc89 go: finding github.com/russross/blackfriday v1.5.2 go: error loading module requirements Makefile:26: recipe for target 'release' failed make: *** [release] Error 1 root@ip-172-31-36-185:~/go/src/github.com/thetatoken/theta# go version
> go version go1.12.1 linux/amd64
> root@ip-172-31-36-185:~/go/src/github.com/thetatoken/theta# uname -a Linux ip-172-31-36-185 5.4.0-1038-aws #40~18.04.1-Ubuntu SMP Sat Feb 6 01:56:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

What version are you trying to install ?

**Comment by vae520283995** [comment]
> > Failed to build node according to official documentation https://docs.thetatoken.org/docs/setup
> > root@ip-172-31-36-185:~/go/src/github.com/thetatoken/theta# make install go install ./cmd/... go: finding github.com/sirupsen/logrus v1.2.0 go: finding github.com/mattn/go-colorable v0.1.7 go: finding github.com/huin/goupnp v0.0.0-20180415215157-1395d1447324 go: finding github.com/grpc-ecosystem/go-grpc-middleware v1.0.0 go: finding github.com/mitchellh/mapstructure v1.1.2 go: finding github.com/xordataexchange/crypt v0.0.3-0.20170626215501-b2862e3d0a77 go: finding github.com/prometheus/client_golang v0.9.3 go: finding github.com/xiang90/probing v0.0.0-20190116061207-43a291ad63a2 go: finding golang.org/x/net v0.0.0-20190522155817-f3200d17e092 go: finding github.com/coreos/bbolt v1.3.2 go: finding go.uber.org/zap v1.10.0 go: finding github.com/wedeploy/gosocketio v0.0.7-beta go: finding github.com/ipfs/go-ipfs-delay v0.0.0-20181109222059-70721b86a9a8 go: finding github.com/go-check/check v0.0.0-20180628173108-788fd7840127 go: finding github.com/libp2p/go-stream-muxer-multistream v0.2.0 go: github.com/wedeploy/gosocketio@v0.0.7-beta: unknown revision v0.0.7-beta go: finding golang.org/x/net v0.0.0-20181011144130-49bb7cea24b1 go: finding github.com/spf13/cast v1.3.0 go: finding github.com/libp2p/go-libp2p-loggables v0.1.0 go: finding github.com/miekg/dns v1.1.12 go: finding go.uber.org/atomic v1.4.0 go: finding golang.org/x/text v0.3.0 go: finding github.com/btcsuite/goleveldb v0.0.0-20160330041536-7834afc9e8cd go: finding github.com/libp2p/go-libp2p-circuit v0.1.1 go: finding github.com/fsnotify/fsnotify v1.4.7 go: finding gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405 go: finding golang.org/x/sys v0.0.0-20180905080454-ebe1bf3edb33 go: finding github.com/pion/sctp v1.7.3 go: finding github.com/spf13/jwalterweatherman v1.0.0 go: finding github.com/google/go-cmp v0.2.0 go: finding github.com/google/uuid v1.1.1 go: finding github.com/jbenet/go-cienv v0.1.0 go: finding github.com/onsi/gomega v1.4.3 go: finding golang.org/x/net v0.0.0-20190311183353-d8887717615a go: finding golang.org/x/crypto v0.0.0-20181203042331-505ab145d0a9 go: finding golang.org/x/sys v0.0.0-20190412213103-97732733099d go: finding github.com/libp2p/go-maddr-filter v0.0.5 go: finding github.com/coreos/etcd v3.3.10+incompatible go: finding gopkg.in/check.v1 v1.0.0-20190902080502-41f04d3bba15 go: finding github.com/mgutz/ansi v0.0.0-20200706080929-d51e80ef957d go: finding github.com/gorilla/websocket v1.4.0 go: finding github.com/konsorten/go-windows-terminal-sequences v1.0.1 go: finding github.com/btcsuite/btclog v0.0.0-20170628155309-84c8d2346e9f go: finding github.com/kkdai/bstream v0.0.0-20161212061736-f391b8402d23 go: finding gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127 go: finding github.com/grpc-ecosystem/go-grpc-prometheus v1.2.0 go: finding github.com/ipfs/go-ipfs-util v0.0.1 go: finding github.com/libp2p/go-libp2p-yamux v0.2.1 go: finding github.com/libp2p/go-libp2p-mplex v0.2.1 go: finding github.com/libp2p/go-libp2p-netutil v0.1.0 go: finding github.com/dgrijalva/jwt-go v3.2.0+incompatible go: finding github.com/soheilhy/cmux v0.1.4 go: finding github.com/subosito/gotenv v1.2.0 go: finding go.uber.org/multierr v1.1.0 go: finding github.com/libp2p/go-libp2p-blankhost v0.1.3 go: finding golang.org/x/crypto v0.0.0-20170930174604-9419663f5a44 go: finding github.com/ugorji/go/codec v0.0.0-20181204163529-d75b2dcb6bc8 go: finding github.com/spf13/afero v1.1.2 go: finding github.com/btcsuite/btcutil v0.0.0-20190207003914-4c204d697803 go: finding github.com/jrick/logrotate v1.0.0 go: finding golang.org/x/net v0.0.0-20180524181706-dfa909b99c79 go: finding github.com/libp2p/go-libp2p-autonat v0.1.0 go: finding golang.org/x/crypto v0.0.0-20180904163835-0709b304e793 go: finding github.com/libp2p/go-ws-transport v0.1.0 go: finding golang.org/x/time v0.0.0-20190308202827-9d24e82272b4 go: finding github.com/huin/goutil v0.0.0-20170803182201-1ca381bf3150 go: finding github.com/whyrusleeping/mdns v0.0.0-20180901202407-ef14215e6b30 go: finding github.com/hashicorp/hcl v1.0.0 go: finding github.com/coreos/go-etcd v2.0.0+incompatible go: finding github.com/btcsuite/winsvc v1.0.0 go: finding github.com/golang/groupcache v0.0.0-20190129154638-5b532d6fd5ef go: finding google.golang.org/genproto v0.0.0-20190307195333-5fe7a883aa19 go: finding github.com/davecgh/go-spew v0.0.0-20171005155431-ecdeabc65495 go: finding github.com/multiformats/go-multiaddr-dns v0.0.2 go: finding golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2 go: finding github.com/libp2p/go-libp2p-secio v0.2.0 go: finding golang.org/x/sys v0.0.0-20181205085412-a5c9d58dba9a go: finding github.com/libp2p/go-tcp-transport v0.1.0 go: finding golang.org/x/sys v0.0.0-20190422165155-953cdadca894 go: finding github.com/tmc/grpc-websocket-proxy v0.0.0-20190109142713-0ad062ec5ee5 go: finding github.com/pelletier/go-toml v1.2.0 go: finding google.golang.org/grpc v1.19.0 go: finding github.com/coreos/go-systemd v0.0.0-20190321100706-95778dfbb74e go: finding github.com/libp2p/go-libp2p-transport-upgrader v0.1.1 go: finding golang.org/x/net v0.0.0-20190404232315-eb5bcb51f2a3 go: finding github.com/libp2p/go-eventbus v0.0.2 go: finding github.com/stretchr/objx v0.1.1 go: finding github.com/libp2p/go-libp2p-discovery v0.1.0 go: finding github.com/golang/protobuf v1.2.0 go: finding github.com/stretchr/testify v1.2.2 go: finding github.com/magiconair/properties v1.8.1 go: finding github.com/libp2p/go-conn-security-multistream v0.1.0 go: finding github.com/armon/consul-api v0.0.0-20180202201655-eb2c6b5be1b6 go: finding github.com/libp2p/go-libp2p-nat v0.0.4 go: finding github.com/coreos/go-semver v0.2.0 go: finding github.com/ugorji/go v1.1.4 go: finding github.com/libp2p/go-libp2p-testing v0.1.0 go: finding github.com/btcsuite/snappy-go v0.0.0-20151229074030-0bdef8d06723 go: finding github.com/btcsuite/websocket v0.0.0-20150119174127-31079b680792 go: finding github.com/coreos/pkg v0.0.0-20180928190104-399ea9e2e55f go: finding github.com/grpc-ecosystem/grpc-gateway v1.9.0 go: finding github.com/magiconair/properties v1.8.0 go: finding google.golang.org/grpc v1.21.0 go: finding github.com/btcsuite/go-socks v0.0.0-20170105172521-4720035b7bfd go: finding go.etcd.io/bbolt v1.3.2 go: finding golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a go: finding github.com/hashicorp/golang-lru v0.5.0 go: finding github.com/jackpal/gateway v1.0.4 go: finding github.com/aead/siphash v1.0.1 go: finding github.com/jonboulle/clockwork v0.1.0 go: finding github.com/kr/pretty v0.1.0 go: finding github.com/onsi/ginkgo v1.7.0 go: finding github.com/google/btree v1.0.0 go: finding github.com/jessevdk/go-flags v0.0.0-20141203071132-1679536dcc89 go: finding github.com/russross/blackfriday v1.5.2 go: error loading module requirements Makefile:26: recipe for target 'release' failed make: *** [release] Error 1 root@ip-172-31-36-185:~/go/src/github.com/thetatoken/theta# go version
> > go version go1.12.1 linux/amd64
> > root@ip-172-31-36-185:~/go/src/github.com/thetatoken/theta# uname -a Linux ip-172-31-36-185 5.4.0-1038-aws #40~18.04.1-Ubuntu SMP Sat Feb 6 01:56:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
> 
> What version are you trying to install ?

root@ip-172-31-38-16:~/go/src/github.com/thetatoken/theta# git branch
* release

**Comment by FrankP01** [comment]
> > What version are you trying to install ?
> 
> root@ip-172-31-38-16:~/go/src/github.com/thetatoken/theta# git branch
> 
> * release

I will advise you join the Theta Telegram channel by following the web link below https://t.me/thetanetworking (39k members)  they will be glad to help you . Cheers

**Comment by networkpunk** [comment]
Build the master branch

**Comment by vae520283995** [comment]
> Build the master branch

go: finding github.com/libp2p/go-libp2p-testing v0.0.3
go: finding github.com/libp2p/go-buffer-pool v0.0.2
go: finding github.com/multiformats/go-multihash v0.0.1
go: finding github.com/jessevdk/go-flags v0.0.0-20141203071132-1679536dcc89
go: finding github.com/kkdai/bstream v0.0.0-20161212061736-f391b8402d23
go: finding github.com/onsi/gomega v1.5.0
go: finding golang.org/x/sys v0.0.0-20200223170610-d5e6a3e2c0ae
go: finding github.com/opentracing/opentracing-go v1.0.2
go: finding github.com/libp2p/go-mplex v0.1.0
go: finding github.com/libp2p/go-maddr-filter v0.0.4
go: finding github.com/jbenet/goprocess v0.1.3
go: finding github.com/pion/transport v0.6.0
go: error loading module requirements
Makefile:26: recipe for target 'release' failed
make: *** [release] Error 1
root@ip-172-31-38-16:~/go/src/github.com/thetatoken/theta# git branch
* release
root@ip-172-31-38-16:~/go/src/github.com/thetatoken/theta# go version
go version go1.12.1 linux/amd64

**Comment by vae520283995** [comment]
> Build the master branch

go: finding golang.org/x/sys v0.0.0-20191001151750-bb3f8db39f24
go: finding github.com/pion/mdns v0.0.3
go: finding github.com/grpc-ecosystem/grpc-gateway v1.9.0
go: finding github.com/pion/turn v1.4.0
go: finding github.com/libp2p/go-addr-util v0.0.1
go: finding github.com/konsorten/go-windows-terminal-sequences v1.0.1
go: finding github.com/mattn/go-colorable v0.1.7
go: finding golang.org/x/sys v0.0.0-20190412213103-97732733099d
go: finding github.com/coreos/bbolt v1.3.2
go: finding github.com/pelletier/go-toml v1.2.0
go: finding golang.org/x/net v0.0.0-20190311183353-d8887717615a
go: finding github.com/libp2p/go-libp2p-yamux v0.2.0
go: finding github.com/armon/consul-api v0.0.0-20180202201655-eb2c6b5be1b6
go: finding github.com/gorilla/websocket v1.4.0
go: finding github.com/grpc-ecosystem/go-grpc-prometheus v1.2.0
go: finding github.com/libp2p/go-yamux v1.2.3
go: error loading module requirements
Makefile:26: recipe for target 'release' failed
make: *** [release] Error 1

git branch
* master
go version
go version go1.12.1 linux/amd64

**Comment by FrankP01** [comment]
> > Build the master branch
> 
> go: finding golang.org/x/sys v0.0.0-20191001151750-bb3f8db39f24
> go: finding github.com/pion/mdns v0.0.3
> go: finding github.com/grpc-ecosystem/grpc-gateway v1.9.0
> go: finding github.com/pion/turn v1.4.0
> go: finding github.com/libp2p/go-addr-util v0.0.1
> go: finding github.com/konsorten/go-windows-terminal-sequences v1.0.1
> go: finding github.com/mattn/go-colorable v0.1.7
> go: finding golang.org/x/sys v0.0.0-20190412213103-97732733099d
> go: finding github.com/coreos/bbolt v1.3.2
> go: finding github.com/pelletier/go-toml v1.2.0
> go: finding golang.org/x/net v0.0.0-20190311183353-d8887717615a
> go: finding github.com/libp2p/go-libp2p-yamux v0.2.0
> go: finding github.com/armon/consul-api v0.0.0-20180202201655-eb2c6b5be1b6
> go: finding github.com/gorilla/websocket v1.4.0
> go: finding github.com/grpc-ecosystem/go-grpc-prometheus v1.2.0
> go: finding github.com/libp2p/go-yamux v1.2.3
> go: error loading module requirements
> Makefile:26: recipe for target 'release' failed
> make: *** [release] Error 1
> 
> git branch
> 
> * master
>   go version
>   go version go1.12.1 linux/amd64

I will advise you join the Theta Telegram channel by following the web link below https://t.me/thetanetworking (39k members) they will be glad to help you . Cheers

**Comment by vae520283995** [comment]
I gave up installing from the source code and downloaded the latest linux binary directly
