### ISSUE TITLE
Old theta token to theta mainnet wallet

### ISSUE THREAD

**Issue by Westphil57** [thetatoken/theta-protocol-ledger#202]
I acquired theta tokens on the ethereum blockchain using matamask and ledger nano X.

I downloaded the theta mainnet wallet and my tokens do not appear on the theta mainnet with my nano X ledger.
On etherscan they are present
My theta wallet remains at 0.
![Capture d’écran 2023-04-26 075127](https://user-images.githubusercontent.com/56757974/234482668-5ba5d3dc-4b9d-44a1-a518-71c526c3fdf3.png)

 I paid 10 theta Tokens from metamask to my another theta mainnet wallet with mnemonic: and they are not visible.

Please give me the procedure to follow with my ledger nano X.

**Comment by ThetaNetworkForGithub** [comment]
@Westphil57 Sorry to hear about this issue and we apologise for any inconvenience caused by this. Kindly reach out to the Theta Team on the ThetaNetwork telegram via the weblink https://t.me/thetanetworking
They'll be happy to resolve your issue. Cheers.

**Comment by ThetaNetworkForGithub** [comment]
@Westphil57 Sorry to hear about this issue and we apologise for any inconvenience caused by this. Kindly reach out to the Theta Team on the ThetaNetwork telegram via the weblink https://t.me/thetanetworking
They'll be happy to resolve your issue. Cheers.

**Comment by Westphil57** [comment]
f
