### ISSUE TITLE
 Whether the  configuration of the mainnet node which were running were the same as the  public source  code?

### ISSUE THREAD

**Issue by lrl219** [thetatoken/theta-protocol-ledger#38]
As the title above, such as MaxNumRegularTxsPerBlock,MaxAccountsAffectedPerTx and etc...

**Comment by jieyilong** [comment]
We will update the mainnet config shortly. Thanks!

**Comment by jieyilong** [comment]
Updated mainnet config: https://github.com/thetatoken/theta-protocol-ledger/commit/67fb85f6b9486954a470eb1d03d8a01ed67fc119

See also: https://github.com/thetatoken/theta-mainnet-integration-guide/blob/master/docs/mainnet.md#connect-to-the-mainnet
