### ISSUE TITLE
mainnet  connecting to  send peers

### ISSUE THREAD

**Issue by zhanghoufu** [thetatoken/theta-protocol-ledger#44]
I runmainnet   get the error ：
2019-04-12 16:30:18]  INFO [p2p] Connecting to seed peers...
                                                                                                        │[2019-04-12 16:30:20]  INFO [p2p] Connecting to outbound peer: 18.222.201.29:21000...
                                                                                                        │[2019-04-12 16:30:21]  INFO [p2p] Connecting to outbound peer: 18.218.16.108:21000...
                                                                                                        │[2019-04-12 16:30:21]  INFO [p2p] Connecting to outbound peer: 18.191.88.191:21000...
                                                                                                        │[2019-04-12 16:30:30]  WARN [p2p] Error dialing the peer: 18.222.201.29:21000
                                                                                                        │[2019-04-12 16:30:30]  WARN [p2p] Failed to create outbound peer: 18.222.201.29:21000
                                                                                                        │[2019-04-12 16:30:31]  WARN [p2p] Error dialing the peer: 18.218.16.108:21000
                                                                                                        │[2019-04-12 16:30:31]  WARN [p2p] Failed to create outbound peer: 18.218.16.108:21000
                                                                                                        │[2019-04-12 16:30:31]  WARN [p2p] Error dialing the peer: 18.191.88.191:21000
                                                                                                        │[2019-04-12 16:30:31]  WARN [p2p] Failed to create outbound peer: 18.191.88.191:21000
                                                                                                        │[2019-04-12 16:30:48]  INFO [p2p] Connecting to seed peers...
                                                                                                        │[2019-04-12 16:30:49]  INFO [p2p] Connecting to outbound peer: 18.191.88.191:21000...
                                                                                                        │[2019-04-12 16:30:49]  INFO [p2p] Connecting to outbound peer: 18.222.201.29:21000...
                                                                                                        │[2019-04-12 16:30:49]  INFO [p2p] Connecting to outbound peer: 18.218.16.108:21000...

**Comment by jieyilong** [comment]
We will update the mainnet config and document shortly. Thanks!

**Comment by haivp3010** [comment]
Hello @jieyilong, has this issue been addressed? I followed the guide to set up a node connecting to mainnet but it just stuck at
```
INFO [p2p] Connecting to seed peers...
INFO [p2p] Connecting to seed peers...
INFO [p2p] Connecting to seed peers...
...
```

**Comment by dragon930731** [comment]
how to mainnet connect?
Hello Theta >> Theta node pwd >> INFO [p2p] Connecting to seed peers...   
Repeat every 30 seconds
help me

**Comment by DreamHackchosenone** [comment]
> We will update the mainnet config and document shortly. Thanks!

still  not work 
│[2019-04-12 16:30:49] INFO [p2p] Connecting to outbound peer: 18.191.88.191:21000...
│[2019-04-12 16:30:49] INFO [p2p] Connecting to outbound peer: 18.222.201.29:21000...
│[2019-04-12 16:30:49] INFO [p2p] Connecting to outbound peer: 18.218.16.108:21000.

**Comment by jieyilong** [comment]
Updated mainnet config: https://github.com/thetatoken/theta-protocol-ledger/commit/67fb85f6b9486954a470eb1d03d8a01ed67fc119

See also: https://github.com/thetatoken/theta-mainnet-integration-guide/blob/master/docs/mainnet.md#connect-to-the-mainnet
