### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by shazbert** [thetatoken/theta-protocol-ledger#49]
Is there a reason why you don't have CI/linter/codecov integration?
Do you accept public PR's?
Is there a developer channel either on slack or on telegram?

**Comment by larrydear** [comment]
Agreed, hope theta dev team to be more open.

**Comment by shazbert** [comment]
I only ask because I want to help with this project. Any communication would be appreciated.

**Comment by Yoruba** [comment]
You can push PR's if you want. I did it already a couple of time's.

**Comment by shazbert** [comment]
@Yoruba Okay, fantastic thanks for the info.

**Comment by Yoruba** [comment]
@shazbert can you please close this issue if you don't have any questions more?

Thanks

**Comment by shazbert** [comment]
@Yoruba issue closed
