### ISSUE TITLE
i'd like to know public theta node url....

### ISSUE THREAD

**Issue by leeheejoo** [thetatoken/theta-protocol-ledger#60]
mainnet block synchronization is too slow.
so i want to know the public node url. 
to do rpc testing.

**Comment by luisiiyoo** [comment]
Hello @leeheejoo 
Could you share your config.yaml, I'm having issues with connecting to peers, on my config.yaml is not defined the seeds.

**Comment by jieyilong** [comment]
Updated mainnet config: https://github.com/thetatoken/theta-protocol-ledger/commit/67fb85f6b9486954a470eb1d03d8a01ed67fc119

See also: https://github.com/thetatoken/theta-mainnet-integration-guide/blob/master/docs/mainnet.md#connect-to-the-mainnet
