### ISSUE TITLE
Connection refused on all RPC API thetacli key CMD

### ISSUE THREAD

**Issue by Yoruba** [thetatoken/theta-protocol-ledger#75]
For example List Keys cmd

```
curl -X POST -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"thetacli.ListKeys","params":[],"id":1}' http://localhost:16889/rpc
```

Gives an error.
```
curl: (7) Failed to connect to localhost port 16889: Connection refused
```

This was working a year ago. 
Maybe it is refused because of security reasons?

Thanks

**Comment by jieyilong** [comment]
Is your RPC port 16889 or 16888? Also did you enable RPC in config.yaml?

**Comment by Yoruba** [comment]
RPC ports are the default ports and not set in the config.yaml
RPC is enabled

Calls to theta API with port 16888 are working
Calls to thetacli API with port 16889 are not working 

if I do a netstat port, 16889 is not listening

**Comment by jieyilong** [comment]
yeah if you didn't specify 16889 as the RPC port in config.yaml, by default the node will use 16888 as the RPC port

**Comment by Yoruba** [comment]
There are 2 ports needed. 1 for Theta API (node) and 1 for Theta cli API (wallet).
Port 16888 is for node API that one is working.
Port 16889 is for the wallet API and that port is not listening by default.

The node calls are working but you can call the wallet calls on the same port as the node port.

**Comment by jieyilong** [comment]
I see, did you run the thetacli deamon? Need the deamon process in the background to enable the API on port 16889

thetacli daemon start --port=16889

**Comment by Yoruba** [comment]
Thanks @jieyilong it is working.
