### ISSUE TITLE
Where can I download the snapshot files needed for Theta mainnet node startup?

### ISSUE THREAD

**Issue by caokun8008** [thetatoken/theta-protocol-ledger#80]
Where can I download the snapshot files needed for Theta mainnet node startup?can anyone tell me? Thanks

**Comment by bitcodernull** [comment]
i  also  want to know

**Comment by jieyilong** [comment]
We will post the instructions for connecting to the mainnet shortly. Thanks!

**Comment by jieyilong** [comment]
The latest mainnet snapshot can be downloaded with

wget -O ./snapshot `curl -k https://mainnet-data.thetatoken.org/snapshot`

See also: https://github.com/thetatoken/theta-mainnet-integration-guide/blob/master/docs/mainnet.md#connect-to-the-mainnet
