### ISSUE TITLE
How to send a zero-fee transaction?

### ISSUE THREAD

**Issue by zenghq3** [thetatoken/theta-protocol-ledger#90]
I see a zero-fee transaction in the block explorer
`https://explorer.thetatoken.org/txs/0x801c54e531ef2b96cbfdf69dc539a6d0d1129b89cb527a3e46277df3a765a223`
But  I use the privatenet,  assembled the transaction and got 
`{"code":-32000,"message":"Insufficient fee. Transaction fee needs to be at least 1000000000000 TFuelWei"}`
This is my transaction structure
```
inputs := []types.TxInput{{
		Address: from,
		Coins: types.Coins{
			TFuelWei: new(big.Int).SetUint64(0),
			ThetaWei: theta,
		},
		Sequence: uint64(seq),
	}}
	outputs := []types.TxOutput{{
		Address: common.HexToAddress(toAddress),
		Coins: types.Coins{
			TFuelWei: new(big.Int).SetUint64(0),
			ThetaWei: theta,
		},
	}}
	sendTx := &types.SendTx{
		Fee: types.Coins{
			ThetaWei: new(big.Int).SetUint64(0),
			TFuelWei: new(big.Int).SetUint64(0),
		},
		Inputs:  inputs,
		Outputs: outputs,
	}
```
Can you tell me how to send a zero-fee transaction? And tell me the difference between Theta and TFuel, the document link is also OK. Thanks

**Comment by ygcool** [comment]
hi, Can I add your contact information? qq or vx or telegram
