### ISSUE TITLE
Server returned error: 0: Timeout

### ISSUE THREAD

**Issue by oggy95** [thetatoken/theta-protocol-ledger#99]
Hello.

After updating to version 2.1.0 we getting an errors on withdrawing theta and tfuel.
While sending some theta or tfuel via api (thetacli.Send, async=false), request executes very long and sometimes we getting this error:

```
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32000,
    "message": "Server returned error: 0: Timeout"
  }
}
```

But transaction successfully pushed to blockchain.
In logs theta:
`[2020-12-11 09:09:42] ERROR [rpc] HTTP request timed out: requestBody={"{\"jsonrpc\":\"2.0\",\"method\":\"theta.BroadcastRawTransaction\",\"params\":[{\"tx_bytes\":\"SOME_TX_BYTES\"}],\"id\":0}"}
`

Request body:

```
{
	"jsonrpc": "2.0",
	"method": "thetacli.Send",
	"params": {
		"chain_id": "mainnet",
		"from": ADDRESS_FROM,
		"to": ADDRESS_TO,
		"thetawei": "0",
		"tfuelwei": SOME_TFUEL,
		"fee":"1000000000000",
		"sequence": "SOME_SEQUENCE,
		"async": false
	},
	"id": 1
}
```
Switch to async transactions we can't.

**Comment by jieyilong** [comment]
Thanks for reporting the issue. I assume you're running the Theta software on Linux? Are you running the Theta software with the downloaded binaries or compiling from the source code?

**Comment by oggy95** [comment]
Yes, Ubuntu 18.04.
Compiling from the source code.

**Comment by jieyilong** [comment]
Thanks. We have just committed a fix for this issue a few hours ago to the `master` branch:

https://github.com/thetatoken/theta-protocol-ledger/commit/3cdaba15934dbed967f11291bb99955d566ac474

Could you pull the latest code from the `master` branch and see if you still see the issue? We'll merge the changes to the `release` branch later after more thorough testing.

**Comment by oggy95** [comment]
Some transactions proceed faster, but errors still appear on some of them.

**Comment by jieyilong** [comment]
We rolled out a fix to the validators a few days ago. Please let us know if you still see the errors.

**Comment by oggy95** [comment]
No, error still appears.
We switched to async tx, therefore, the problem is not relevant at the moment.
